apiVersion: v1
kind: PersistentVolume
metadata:
  name: verbum-publicum-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume"
    type: DirectoryOrCreate
