apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verbum-publicum-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: verbum-publicum-pv
