
ingress:
  enabled: true
  className: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
  hosts:
    - host: coopoasissauve.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: wp.localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

wordpress:
  wordpressBlogName: "verbum publicum"
  resources:
    requests:
      memory: 2Gi
      cpu: 2000m
  ingress:
    enabled: false
    ingressClassName: "nginx"
    hostname: "wp.localhost"
  wordpressScheme: "https"
  wordpressExtraConfigContent: |
    // running it in a cloudflare tunnel (tls from cloudflare and localhost on port 80)
    $_SERVER['HTTPS'] = 'on';
  extraVolumes:
  - name: data
    persistentVolumeClaim:
      claimName: verbum-publicum-pvc
  extraVolumeMounts:
  - name: data
    mountPath: /opt/volume
