nextcloud:
  nextcloud:
    host: "intra.localhost"
    existingSecret:
      enabled: true
      secretName: nextcloud-secrets
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      tokenKey: nextcloud-token
  ingress:
    enabled: true
    className: "nginx"
    tls:
      - secretName: intra-selfsigned-cert
        hosts:
          - intra.localhost

wordpress:
  wordpressBlogName: "verbum publicum"
  existingSecret: "wordpress-secrets"
  mariadb:
    externalDatabase:
      existingSecret: "nextcloud-mariadb-secrets"
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "wp.localhost"
  wordpressExtraConfigContent: |
    // running it in a cloudflare tunnel (tls from cloudflare and localhost on port 80)
    $_SERVER['HTTPS'] = 'on';
  extraVolumes:
  - name: data
    persistentVolumeClaim:
      claimName: verbum-publicum-pvc
  extraVolumeMounts:
  - name: data
    mountPath: /opt/volume
