name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3

      - run: cp sample.env .env
      - run: make ci

      - if: github.ref == 'refs/heads/main'
        run: |
          echo "production hook..."
